package Model;
// Generated 12 ene 2024 22:06:41 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Citas generated by hbm2java
 */
public class Citas implements java.io.Serializable {

	private Integer citaId;
	private Usuarios usuariosByUsuarioSolicitanteId;
	private Usuarios usuariosByUsuarioDestinoId;
	private Set likescitases = new HashSet(0);

	public Citas() {
	}

	public Citas(Usuarios usuariosByUsuarioSolicitanteId, Usuarios usuariosByUsuarioDestinoId, Set likescitases) {
		this.usuariosByUsuarioSolicitanteId = usuariosByUsuarioSolicitanteId;
		this.usuariosByUsuarioDestinoId = usuariosByUsuarioDestinoId;
		this.likescitases = likescitases;
	}

	public Integer getCitaId() {
		return this.citaId;
	}

	public void setCitaId(Integer citaId) {
		this.citaId = citaId;
	}

	public Usuarios getUsuariosByUsuarioSolicitanteId() {
		return this.usuariosByUsuarioSolicitanteId;
	}

	public void setUsuariosByUsuarioSolicitanteId(Usuarios usuariosByUsuarioSolicitanteId) {
		this.usuariosByUsuarioSolicitanteId = usuariosByUsuarioSolicitanteId;
	}

	public Usuarios getUsuariosByUsuarioDestinoId() {
		return this.usuariosByUsuarioDestinoId;
	}

	public void setUsuariosByUsuarioDestinoId(Usuarios usuariosByUsuarioDestinoId) {
		this.usuariosByUsuarioDestinoId = usuariosByUsuarioDestinoId;
	}

	public Set getLikescitases() {
		return this.likescitases;
	}

	public void setLikescitases(Set likescitases) {
		this.likescitases = likescitases;
	}

}
