package Model;
// Generated 12 ene 2024 22:06:41 by Hibernate Tools 6.3.1.Final

/**
 * Participanteseventos generated by hbm2java
 */
public class Participanteseventos implements java.io.Serializable {

	private Integer participanteEventoId;
	private Eventos eventos;
	private Usuarios usuarios;

	public Participanteseventos() {
	}

	public Participanteseventos(Eventos eventos, Usuarios usuarios) {
		this.eventos = eventos;
		this.usuarios = usuarios;
	}

	public Integer getParticipanteEventoId() {
		return this.participanteEventoId;
	}

	public void setParticipanteEventoId(Integer participanteEventoId) {
		this.participanteEventoId = participanteEventoId;
	}

	public Eventos getEventos() {
		return this.eventos;
	}

	public void setEventos(Eventos eventos) {
		this.eventos = eventos;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
