package Model;
// Generated 12 ene 2024 22:06:41 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer userId;
	private String nombreUsuario;
	private String numeroTelefono;
	private String correoElectronico;
	private String genero;
	private String localidad;
	private String descripcion;
	private String contraseña;
	private Set citasesForUsuarioSolicitanteId = new HashSet(0);
	private Set participanteseventoses = new HashSet(0);
	private Set likescitases = new HashSet(0);
	private Set eventoses = new HashSet(0);
	private Set likeseventoses = new HashSet(0);
	private Set citasesForUsuarioDestinoId = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String nombreUsuario, String numeroTelefono, String correoElectronico, String genero, String localidad, String descripcion, String contraseña, Set citasesForUsuarioSolicitanteId, Set participanteseventoses, Set likescitases, Set eventoses, Set likeseventoses, Set citasesForUsuarioDestinoId) {
       this.nombreUsuario = nombreUsuario;
       this.numeroTelefono = numeroTelefono;
       this.correoElectronico = correoElectronico;
       this.genero = genero;
       this.localidad = localidad;
       this.descripcion = descripcion;
       this.contraseña = contraseña;
       this.citasesForUsuarioSolicitanteId = citasesForUsuarioSolicitanteId;
       this.participanteseventoses = participanteseventoses;
       this.likescitases = likescitases;
       this.eventoses = eventoses;
       this.likeseventoses = likeseventoses;
       this.citasesForUsuarioDestinoId = citasesForUsuarioDestinoId;
    }

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getNumeroTelefono() {
		return this.numeroTelefono;
	}

	public void setNumeroTelefono(String numeroTelefono) {
		this.numeroTelefono = numeroTelefono;
	}

	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getContraseña() {
        return this.contraseña;
    }

	public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }

	public Set getCitasesForUsuarioSolicitanteId() {
		return this.citasesForUsuarioSolicitanteId;
	}

	public void setCitasesForUsuarioSolicitanteId(Set citasesForUsuarioSolicitanteId) {
		this.citasesForUsuarioSolicitanteId = citasesForUsuarioSolicitanteId;
	}

	public Set getParticipanteseventoses() {
		return this.participanteseventoses;
	}

	public void setParticipanteseventoses(Set participanteseventoses) {
		this.participanteseventoses = participanteseventoses;
	}

	public Set getLikescitases() {
		return this.likescitases;
	}

	public void setLikescitases(Set likescitases) {
		this.likescitases = likescitases;
	}

	public Set getEventoses() {
		return this.eventoses;
	}

	public void setEventoses(Set eventoses) {
		this.eventoses = eventoses;
	}

	public Set getLikeseventoses() {
		return this.likeseventoses;
	}

	public void setLikeseventoses(Set likeseventoses) {
		this.likeseventoses = likeseventoses;
	}

	public Set getCitasesForUsuarioDestinoId() {
		return this.citasesForUsuarioDestinoId;
	}

	public void setCitasesForUsuarioDestinoId(Set citasesForUsuarioDestinoId) {
		this.citasesForUsuarioDestinoId = citasesForUsuarioDestinoId;
	}

}
