/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.cBienvenida;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import lombok.Getter;

/**
 * The type Bienvenida.
 *
 * @author Pedro Rollán García
 */
@Getter
public class Bienvenida extends javax.swing.JFrame {

  /**
   * Creates new form Bienvenida
   */
  public Bienvenida() {
    setVisible(true);
    FlatIntelliJLaf.setup();
    FlatLightLaf.setup();
    initComponents();
    cBienvenida Controlador = new cBienvenida(this);
    Controlador.actualizarEstilos();

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel12 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jLabel25 = new javax.swing.JLabel();
    jLabel26 = new javax.swing.JLabel();
    jLabel29 = new javax.swing.JLabel();
    jLabel30 = new javax.swing.JLabel();
    jLabel31 = new javax.swing.JLabel();
    jLabel32 = new javax.swing.JLabel();
    jLabel33 = new javax.swing.JLabel();
    jLabel34 = new javax.swing.JLabel();
    jLabel35 = new javax.swing.JLabel();
    jLabel36 = new javax.swing.JLabel();
    jLabel37 = new javax.swing.JLabel();
    jLabel38 = new javax.swing.JLabel();
    jLabel39 = new javax.swing.JLabel();
    jLabel40 = new javax.swing.JLabel();
    jLabel41 = new javax.swing.JLabel();
    jLabel42 = new javax.swing.JLabel();
    jLabel43 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    searchTf = new javax.swing.JTextField();
    panelAbsoluto = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(53, 49, 48));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel3.setBackground(new java.awt.Color(75, 76, 73));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 25)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("BIENVENIDOS A KOIRYU");
    jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 78, 327, 39));

    jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("<html>\n<div style=\"text-align:justify;\">\nOs damos la bienvenida a Koiryu, Creada por alumnos del ciclo de Desarrollo  de Aplicaciones Multiplataforma.Esta idea para el proyecto fue ideada en la  asignatura de Empresa e iniciativa emprendedora donde trabajamos la idea de  proyecto y ahora gracias a las asignaturas de Desarrollo de Interfaces y Acceso  a datos le daremos forma y funcionalidad a la misma. Os recibimos a todos con  los brazos abiertos y esperamos que disfruteis de la experiencia. \n</div>\n</hmtl>");
    jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 198, 763, 166));

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoKoiryu_Blanco_sin_fondo_pequeña.png"))); // NOI18N
    jLabel6.setText("jLabel6");
    jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 73, 51, 44));

    getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 349, 821, 395));

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen hojas 1.png"))); // NOI18N
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 67, 1143, 429));

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Open Door.png"))); // NOI18N
    jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 18, 30, 30));

    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoKoiryu_Blanco_sin_fondo_pequeña 1.png"))); // NOI18N
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1348, 13, 40, 40));

    jPanel1.setBackground(new java.awt.Color(51, 51, 51));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(145, 158, 171));
    jLabel12.setText("Arte");
    jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 50, 18));

    jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    jLabel16.setForeground(new java.awt.Color(99, 115, 129));
    jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/solar_heart-broken.png"))); // NOI18N
    jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 370, 16, 16));

    jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 26)); // NOI18N
    jLabel17.setForeground(new java.awt.Color(159, 255, 0));
    jLabel17.setText("Koiryu");
    jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, 90, 31));

    jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    jLabel25.setForeground(new java.awt.Color(145, 158, 171));
    jLabel25.setText("Home");
    jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 18));

    jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    jLabel26.setForeground(new java.awt.Color(145, 158, 171));
    jLabel26.setText("Naturaleza");
    jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 246, 80, 18));

    jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    jLabel29.setForeground(new java.awt.Color(145, 158, 171));
    jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Frame 588.png"))); // NOI18N
    jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 220, 20, 18));

    jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    jLabel30.setForeground(new java.awt.Color(145, 158, 171));
    jLabel30.setText("Festivales");
    jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 194, 80, -1));

    jLabel31.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    jLabel31.setForeground(new java.awt.Color(145, 158, 171));
    jLabel31.setText("Descubrir");
    jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 370, 80, 18));

    jLabel32.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    jLabel32.setForeground(new java.awt.Color(145, 158, 171));
    jLabel32.setText("Crear Evento");
    jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 280, 110, 18));

    jLabel33.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    jLabel33.setForeground(new java.awt.Color(145, 158, 171));
    jLabel33.setText("Eventos");
    jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 160, 60, 18));

    jLabel34.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    jLabel34.setForeground(new java.awt.Color(99, 115, 129));
    jLabel34.setText("EVENTOS");
    jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 129, 90, 15));

    jLabel35.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    jLabel35.setForeground(new java.awt.Color(99, 115, 129));
    jLabel35.setText("CITAS");
    jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 338, 90, 15));

    jLabel36.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    jLabel36.setForeground(new java.awt.Color(99, 115, 129));
    jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
    jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 71, 16, 16));

    jLabel37.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    jLabel37.setForeground(new java.awt.Color(99, 115, 129));
    jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chevron-down (1).png"))); // NOI18N
    jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 71, 16, 16));

    jLabel38.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    jLabel38.setForeground(new java.awt.Color(99, 115, 129));
    jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/layout.png"))); // NOI18N
    jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 280, 16, 16));

    jLabel39.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    jLabel39.setForeground(new java.awt.Color(99, 115, 129));
    jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/layers.png"))); // NOI18N
    jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 160, 16, 16));

    jLabel40.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    jLabel40.setForeground(new java.awt.Color(145, 158, 171));
    jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Frame 588.png"))); // NOI18N
    jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 194, 20, 18));

    jLabel41.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    jLabel41.setForeground(new java.awt.Color(145, 158, 171));
    jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Frame 588.png"))); // NOI18N
    jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 246, 20, 18));

    jLabel42.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    jLabel42.setForeground(new java.awt.Color(99, 115, 129));
    jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chevron-down (1).png"))); // NOI18N
    jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 280, 16, 16));

    jLabel43.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    jLabel43.setForeground(new java.awt.Color(99, 115, 129));
    jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chevron-down (1).png"))); // NOI18N
    jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 160, 16, 16));

    jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Usuario");
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 810, -1, 22));

    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/profile.png"))); // NOI18N
    jLabel8.setText("jLabel8");
    jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 801, 40, 40));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 256, 863));

    jPanel2.setBackground(new java.awt.Color(75, 76, 73));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    searchTf.setBackground(new java.awt.Color(52, 53, 50));
    searchTf.setForeground(new java.awt.Color(255, 255, 255));
    jPanel2.add(searchTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 12, 282, 42));

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 0, 1144, 66));

    panelAbsoluto.setBackground(new java.awt.Color(53, 49, 48));
    panelAbsoluto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    getContentPane().add(panelAbsoluto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 65, 1150, 800));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Main.
   *
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Bienvenida().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel25;
  private javax.swing.JLabel jLabel26;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel30;
  private javax.swing.JLabel jLabel31;
  private javax.swing.JLabel jLabel32;
  private javax.swing.JLabel jLabel33;
  private javax.swing.JLabel jLabel34;
  private javax.swing.JLabel jLabel35;
  private javax.swing.JLabel jLabel36;
  private javax.swing.JLabel jLabel37;
  private javax.swing.JLabel jLabel38;
  private javax.swing.JLabel jLabel39;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel40;
  private javax.swing.JLabel jLabel41;
  private javax.swing.JLabel jLabel42;
  private javax.swing.JLabel jLabel43;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel panelAbsoluto;
  private javax.swing.JTextField searchTf;
  // End of variables declaration//GEN-END:variables

}
