/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.cCrearEvento;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ResourceBundle;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Pedro Rollán García
 */
@Getter
@Setter
public class CrearEvento extends javax.swing.JPanel {

  /**
   * Creates new form CrearEvento
   */
  public CrearEvento() {
    setVisible(true);
    FlatIntelliJLaf.setup();
    FlatLightLaf.setup();
    initComponents();
    cCrearEvento Controlador = new cCrearEvento(this);
    Controlador.actualizarEstilos();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSeparator1 = new javax.swing.JSeparator();
    descripcionEvento = new javax.swing.JTextField();
    nombreEvento1 = new javax.swing.JTextField();
    jComboBox1 = new javax.swing.JComboBox<>();
    jSeparator2 = new javax.swing.JSeparator();
    tituloCrear = new javax.swing.JLabel();
    subtituloCrear = new javax.swing.JLabel();
    crearEvento = new javax.swing.JButton();
    tipoEvento = new javax.swing.JLabel();
    nombre = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    volverCrear = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    panelEventos = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jSeparator1.setBackground(new java.awt.Color(196, 205, 213));
    jSeparator1.setForeground(new java.awt.Color(196, 205, 213));
    add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 189, 759, -1));

    descripcionEvento.setBackground(new java.awt.Color(51, 51, 51));
    descripcionEvento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    descripcionEvento.setForeground(new java.awt.Color(145, 158, 171));
    add(descripcionEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 488, 698, 145));

    nombreEvento1.setBackground(new java.awt.Color(51, 51, 51));
    nombreEvento1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
    nombreEvento1.setForeground(new java.awt.Color(145, 158, 171));
    nombreEvento1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nombreEvento1ActionPerformed(evt);
      }
    });
    add(nombreEvento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 365, 491, 41));

    jComboBox1.setBackground(new java.awt.Color(51, 51, 51));
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Festival", "Arte", "Naturaleza", " " }));
    add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 424, 491, 41));

    jSeparator2.setBackground(new java.awt.Color(196, 205, 213));
    jSeparator2.setForeground(new java.awt.Color(196, 205, 213));
    add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 59, 1090, 10));

    tituloCrear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
    tituloCrear.setForeground(new java.awt.Color(255, 255, 255));
    tituloCrear.setText("¡CREA TU PROPIO EVENTO!");
    add(tituloCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 115, 250, 23));

    subtituloCrear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
    subtituloCrear.setForeground(new java.awt.Color(255, 255, 255));
    subtituloCrear.setText("Crea tu propio evento y conoce personas con los mismos gustos con los que disfrutar de actividades multiples ¡Anímate!");
    add(subtituloCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 148, 757, 25));

    crearEvento.setBackground(new java.awt.Color(159, 255, 0));
    crearEvento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    crearEvento.setForeground(new java.awt.Color(0, 0, 0));
    crearEvento.setText("Crear Evento");
    crearEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    add(crearEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 688, 170, 34));

    tipoEvento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    tipoEvento.setForeground(new java.awt.Color(255, 255, 255));
    tipoEvento.setText("Tipo de Evento");
    add(tipoEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 432, 120, 24));

    nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    nombre.setForeground(new java.awt.Color(255, 255, 255));
    nombre.setText("Nombre del evento");
    add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 375, 150, 24));

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadirVerde.png"))); // NOI18N
    jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 40, 40));

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoEvento.png"))); // NOI18N
    add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 218, 124, 124));

    volverCrear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
    volverCrear.setForeground(new java.awt.Color(159, 255, 0));
    volverCrear.setText("Volver al Inicio");
    volverCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    volverCrear.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        volverCrearMouseClicked(evt);
      }
    });
    add(volverCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 25, 130, 19));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salirVerde.png"))); // NOI18N
    jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel9MouseClicked(evt);
      }
    });
    add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 16, 34, 38));

    panelEventos.setBackground(new java.awt.Color(75, 76, 73));
    panelEventos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    add(panelEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 85, 803, 660));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aurora.jpg"))); // NOI18N
    add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 800));
  }// </editor-fold>//GEN-END:initComponents

  private void nombreEvento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEvento1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_nombreEvento1ActionPerformed

  private void volverCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverCrearMouseClicked
    setVisible(false);
    // TODO add your handling code here:
  }//GEN-LAST:event_volverCrearMouseClicked

  private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
    setVisible(false);
    // TODO add your handling code here:
  }//GEN-LAST:event_jLabel9MouseClicked

  public void idiomaInglesCrearEventos() {
    ResourceBundle idioma = ResourceBundle.getBundle("idioma");
    tipoEvento.setText(idioma.getString("CrearEvento.eventType"));
    nombre.setText(idioma.getString("CrearEvento.name"));
    crearEvento.setText(idioma.getString("CrearEvento.createButton"));
    tituloCrear.setText(idioma.getString("CrearEvento.title"));
    subtituloCrear.setText(idioma.getString("CrearEvento.subtitle"));
    volverCrear.setText(idioma.getString("CrearEvento.returnHome"));

  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton crearEvento;
  private javax.swing.JTextField descripcionEvento;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JLabel nombre;
  private javax.swing.JTextField nombreEvento1;
  private javax.swing.JPanel panelEventos;
  private javax.swing.JLabel subtituloCrear;
  private javax.swing.JLabel tipoEvento;
  private javax.swing.JLabel tituloCrear;
  private javax.swing.JLabel volverCrear;
  // End of variables declaration//GEN-END:variables
}
