/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.util.ResourceBundle;

/**
 * Panel para descubrir citas.
 * Este panel proporciona la interfaz gráfica para que los usuarios puedan descubrir citas disponibles.
 * Permite ver información sobre las citas y realizar acciones como agregar fotos, agregar citas, etc.
 *
 * @author Pedro Rollán García
 */
public class DescubrirCitas extends javax.swing.JPanel {

  /**
   * Creates new form DescubrirCitas
   * Constructor de la clase DescubrirCitas.
   * Crea una nueva instancia de DescubrirCitas e inicializa los componentes.
   */
  public DescubrirCitas() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    Español1 = new javax.swing.JLabel();
    Ingles = new javax.swing.JLabel();

    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(159, 255, 0));
    jLabel8.setText("Volver al Inicio");
    jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel8MouseClicked(evt);
      }
    });
    add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 25, 130, 19));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salirVerde.png"))); // NOI18N
    jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel9MouseClicked(evt);
      }
    });
    add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 16, 34, 38));

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Frame 959.png"))); // NOI18N
    jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 382, 40, 40));

    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Frame 960.png"))); // NOI18N
    jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(843, 390, -1, 40));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadirFotoMuyGrande.png"))); // NOI18N
    add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 128, 250, 250));

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Frame 957.png"))); // NOI18N
    jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 477, 60, 60));

    jLabel4.setBackground(new java.awt.Color(53, 49, 48));
    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Frame 958.png"))); // NOI18N
    jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 477, 60, 60));

    jPanel1.setBackground(new java.awt.Color(255, 204, 204));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 25)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(0, 0, 0));
    jLabel6.setText("Usuario");
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 110, -1));

    jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 15)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(0, 0, 0));
    jLabel7.setText("Descripcion");
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 120, -1));

    add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 59, 502, 696));

    jPanel2.setBackground(new java.awt.Color(53, 49, 48));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Español1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/España.png"))); // NOI18N
    Español1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Español1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        Español1MouseClicked(evt);
      }
    });
    jPanel2.add(Español1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, -1, -1));

    Ingles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reino-unido.png"))); // NOI18N
    Ingles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Ingles.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        InglesMouseClicked(evt);
      }
    });
    jPanel2.add(Ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

    add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 800));
  }// </editor-fold>//GEN-END:initComponents

  private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
    setVisible(false);

    // TODO add your handling code here:
  }//GEN-LAST:event_jLabel9MouseClicked

  private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    // TODO add your handling code here:
    setVisible(false);

  }//GEN-LAST:event_jLabel8MouseClicked

  private void Español1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Español1MouseClicked
    // TODO add your handling code here:
    ResourceBundle idioma = ResourceBundle.getBundle("idiomaES");
    jLabel8.setText(idioma.getString("CrearEvento.returnHome"));
  }//GEN-LAST:event_Español1MouseClicked

  private void InglesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InglesMouseClicked
    // TODO add your handling code here:
    ResourceBundle idioma = ResourceBundle.getBundle("idioma");
    jLabel8.setText(idioma.getString("CrearEvento.returnHome"));
  }//GEN-LAST:event_InglesMouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Español1;
  private javax.swing.JLabel Ingles;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
