/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Pedro Rollán García
 */
public class MisEventos extends javax.swing.JPanel {

  /**
   * Creates new form MisEventos
   */
  public MisEventos() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();

    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(159, 255, 0));
    jLabel1.setText("Mis Eventos");
    add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 44, -1, -1));

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
    add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 42, 20, 20));

    jButton1.setBackground(new java.awt.Color(159, 255, 0));
    jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    jButton1.setForeground(new java.awt.Color(0, 0, 0));
    jButton1.setText("Crear Evento");
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 29, 160, 45));

    jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(159, 255, 0));
    jLabel3.setText("Nombre");
    add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 92, -1, -1));

    jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(159, 255, 0));
    jLabel4.setText("Descripción");
    add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 92, -1, -1));

    jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(159, 255, 0));
    jLabel5.setText("Autor");
    add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 92, -1, -1));

    jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(159, 255, 0));
    jLabel6.setText("Tipo");
    add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 92, -1, -1));

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FlechaAbajoVerde.png"))); // NOI18N
    add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 88, -1, -1));

    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FlechaAbajoVerde.png"))); // NOI18N
    add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 88, -1, -1));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FlechaAbajoVerde.png"))); // NOI18N
    add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 88, -1, -1));

    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FlechaAbajoVerde.png"))); // NOI18N
    add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 88, -1, -1));
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  // End of variables declaration//GEN-END:variables
}
