/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.util.ResourceBundle;

/**
 *
 * @author Pedro Rollán García
 */
public class MisEventos extends javax.swing.JPanel {

  /**
   * Creates new form MisEventos
   */
  public MisEventos() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    Español1 = new javax.swing.JLabel();
    Ingles = new javax.swing.JLabel();

    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(159, 255, 0));
    jLabel1.setText("Mis Eventos");
    add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 44, -1, -1));

    jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(159, 255, 0));
    jLabel3.setText("Nombre");
    add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 92, -1, -1));

    jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(159, 255, 0));
    jLabel4.setText("Descripción");
    add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 92, -1, -1));

    jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(159, 255, 0));
    jLabel5.setText("Autor");
    add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 92, -1, -1));

    jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(159, 255, 0));
    jLabel6.setText("Tipo");
    add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 92, -1, -1));

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FlechaAbajoVerde.png"))); // NOI18N
    add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 88, -1, -1));

    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FlechaAbajoVerde.png"))); // NOI18N
    add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 88, -1, -1));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FlechaAbajoVerde.png"))); // NOI18N
    add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 88, -1, -1));

    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FlechaAbajoVerde.png"))); // NOI18N
    add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 88, -1, -1));

    jPanel1.setBackground(new java.awt.Color(53, 49, 48));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Español1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/España.png"))); // NOI18N
    Español1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Español1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        Español1MouseClicked(evt);
      }
    });
    jPanel1.add(Español1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

    Ingles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reino-unido.png"))); // NOI18N
    Ingles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Ingles.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        InglesMouseClicked(evt);
      }
    });
    jPanel1.add(Ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

    add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 800));
  }// </editor-fold>//GEN-END:initComponents

  private void Español1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Español1MouseClicked
    // TODO add your handling code here:
    ResourceBundle idioma = ResourceBundle.getBundle("idiomaES");
    jLabel1.setText(idioma.getString("MisEventos.events"));
    jLabel3.setText(idioma.getString("MisEventos.name"));
    jLabel4.setText(idioma.getString("MisEventos.description"));
    jLabel5.setText(idioma.getString("MisEventos.author"));
    jLabel6.setText(idioma.getString("MisEventos.type"));
  }//GEN-LAST:event_Español1MouseClicked

  private void InglesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InglesMouseClicked
    // TODO add your handling code here:
    ResourceBundle idioma = ResourceBundle.getBundle("idioma");
    jLabel1.setText(idioma.getString("MisEventos.events"));
    jLabel3.setText(idioma.getString("MisEventos.name"));
    jLabel4.setText(idioma.getString("MisEventos.description"));
    jLabel5.setText(idioma.getString("MisEventos.author"));
    jLabel6.setText(idioma.getString("MisEventos.type"));
  }//GEN-LAST:event_InglesMouseClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Español1;
  private javax.swing.JLabel Ingles;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
