/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Pedro Rollán García
 */
public class ModificarPerfil extends javax.swing.JPanel {

  /**
   * Creates new form ModificarPerfil
   */
  public ModificarPerfil() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSeparator2 = new javax.swing.JSeparator();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    panelEventos = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jSeparator2.setBackground(new java.awt.Color(196, 205, 213));
    jSeparator2.setForeground(new java.awt.Color(196, 205, 213));
    add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 59, 1090, 10));

    jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(159, 255, 0));
    jLabel8.setText("Volver al Inicio");
    add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 25, 130, 19));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salirVerde.png"))); // NOI18N
    add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 16, 34, 38));

    jPanel2.setBackground(new java.awt.Color(50, 49, 49));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 800, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 174, Short.MAX_VALUE)
    );

    add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 90, 800, 174));

    panelEventos.setBackground(new java.awt.Color(75, 76, 73));
    panelEventos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    add(panelEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 85, 803, 660));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marcoFlores.jpeg"))); // NOI18N
    add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 800));
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JPanel panelEventos;
  // End of variables declaration//GEN-END:variables
}
