/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Pedro Rollán García
 */
public class RecuperarContraseña extends javax.swing.JFrame {

  /**
   * Creates new form Login
   */
  public RecuperarContraseña() {
    initComponents();
    correoRecuperar.putClientProperty("JTextField.placeholderText", "TuCorreo@Gmail.com");
    correoRecuperar.putClientProperty("FlatLaf.style", "arc:10");

  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    EnviarRecuperar = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel23 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    goToLogin1 = new javax.swing.JLabel();
    correoRecuperar = new javax.swing.JTextField();
    fondo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    EnviarRecuperar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enviar Button.png"))); // NOI18N
    getContentPane().add(EnviarRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 525, 460, 63));

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoKoiryu_Blanco_sin_fondo_pequeña.png"))); // NOI18N
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 26, 40, 40));

    jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 70)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("CONTRASEÑA");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, -1, -1));

    jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 25)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("koiryu");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 30, 80, 32));

    jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("DAM");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 59, 36, 18));

    jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 50)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(43, 159, 110));
    jLabel6.setText("ESPECIAL!");
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 830, 500, 103));

    jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel23.setForeground(new java.awt.Color(43, 159, 110));
    jLabel23.setText("*");
    getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 313, -1, -1));

    jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 50)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(255, 255, 255));
    jLabel12.setText("!CONOCE GENTE");
    getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 775, 444, 103));

    jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(255, 255, 255));
    jLabel15.setText("¿Ya tienes tu nueva contraseña?");
    getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 702, -1, -1));

    jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 70)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("RECUPERAR");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 58, -1, -1));

    jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel16.setForeground(new java.awt.Color(255, 255, 255));
    jLabel16.setText("Se enviará un correo con la nueva contraseña");
    getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 313, -1, -1));

    goToLogin1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    goToLogin1.setForeground(new java.awt.Color(43, 159, 110));
    goToLogin1.setText("¡Logeate!");
    goToLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        goToLogin1MouseClicked(evt);
      }
    });
    getContentPane().add(goToLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 702, -1, -1));

    correoRecuperar.setBackground(new java.awt.Color(12, 50, 36));
    correoRecuperar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    correoRecuperar.setForeground(new java.awt.Color(255, 255, 255));
    getContentPane().add(correoRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 460, 68));

    fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura fondo Login.png"))); // NOI18N
    fondo.setText("jLabel2");
    getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 930));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void goToLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToLogin1MouseClicked
    new Login().setVisible(true);
    new RecuperarContraseña().setVisible(false);    // TODO add your handling code here:
  }//GEN-LAST:event_goToLogin1MouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new RecuperarContraseña().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel EnviarRecuperar;
  private javax.swing.JTextField correoRecuperar;
  private javax.swing.JLabel fondo;
  private javax.swing.JLabel goToLogin1;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  // End of variables declaration//GEN-END:variables
}
